import nmap
import datetime
import sys

def scan_target(target):
    print(f"\n[*] Starting scan on {target}...")
    scanner = nmap.PortScanner()
    scanner.scan(target, arguments='-sV -O')
    return scanner

def generate_report(scanner, target):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Vulnerability Scan Report</title>
    <style>
        body {{ font-family: Arial; margin: 40px; background: #0a0a0a; color: #e0e0e0; }}
        h1 {{ color: #00ff88; }}
        h2 {{ color: #00aaff; border-bottom: 1px solid #333; padding-bottom: 8px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th {{ background: #1a1a2e; color: #00ff88; padding: 10px; text-align: left; }}
        td {{ padding: 10px; border-bottom: 1px solid #222; }}
        .critical {{ color: #ff4444; font-weight: bold; }}
        .high {{ color: #ff8800; font-weight: bold; }}
        .info {{ color: #00aaff; }}
        .open {{ color: #00ff88; }}
        .header-box {{ background: #1a1a2e; padding: 20px; border-radius: 8px; margin-bottom: 30px; }}
    </style>
</head>
<body>
    <div class="header-box">
        <h1>🔍 Network Vulnerability Scan Report</h1>
        <p><strong>Target:</strong> {target}</p>
        <p><strong>Date:</strong> {now}</p>
        <p><strong>Tool:</strong> Python-Nmap Scanner | Analyst: Abudu Rodiyyah</p>
    </div>
"""

    for host in scanner.all_hosts():
        state = scanner[host].state()
        html += f"<h2>Host: {host} — {state.upper()}</h2>"

        # OS Detection
        if 'osmatch' in scanner[host] and scanner[host]['osmatch']:
            os_name = scanner[host]['osmatch'][0]['name']
            html += f"<p><strong>OS Detected:</strong> {os_name}</p>"

        # Port Table
        html += """
        <table>
            <tr>
                <th>Port</th>
                <th>State</th>
                <th>Service</th>
                <th>Version</th>
                <th>Risk</th>
                <th>Recommendation</th>
            </tr>
        """

        risky_ports = {
            21: ("HIGH", "Disable anonymous FTP, use SFTP instead"),
            22: ("INFO", "Ensure SSH key auth only, disable root login"),
            23: ("CRITICAL", "Disable Telnet immediately, use SSH"),
            80: ("HIGH", "Redirect HTTP to HTTPS"),
            443: ("INFO", "Ensure TLS 1.2+ only"),
            3389: ("CRITICAL", "Restrict RDP access, enable NLA"),
            8080: ("HIGH", "Investigate — common malware/proxy port"),
            4444: ("CRITICAL", "Likely malicious — investigate immediately"),
        }

        for proto in scanner[host].all_protocols():
            ports = scanner[host][proto].keys()
            for port in sorted(ports):
                service = scanner[host][proto][port]
                state_p = service['state']
                name = service['name']
                version = service.get('version', '') + ' ' + service.get('extrainfo', '')
                
                risk, rec = risky_ports.get(port, ("LOW", "Monitor regularly"))
                risk_class = risk.lower() if risk in ["CRITICAL", "HIGH"] else "info"

                html += f"""
                <tr>
                    <td><strong>{port}/{proto}</strong></td>
                    <td class="open">{state_p}</td>
                    <td>{name}</td>
                    <td>{version.strip()}</td>
                    <td class="{risk_class}">{risk}</td>
                    <td>{rec}</td>
                </tr>
                """

        html += "</table>"

    html += """
    <h2>Summary & Recommendations</h2>
    <ul>
        <li>Disable all unused ports and services</li>
        <li>Replace unencrypted protocols (Telnet, FTP, HTTP) with encrypted alternatives</li>
        <li>Keep all service versions updated to patch known CVEs</li>
        <li>Implement firewall rules to restrict access to sensitive ports</li>
        <li>Conduct regular scans to detect new exposures</li>
    </ul>
    <p style="color:#555; margin-top:40px;">Report generated by Python-Nmap Vulnerability Scanner — Abudu Rodiyyah</p>
</body>
</html>
"""
    
    filename = f"scan-report-{target.replace('.','_')}.html"
    with open(filename, 'w') as f:
        f.write(html)
    print(f"[+] Report saved to {filename}")
    return filename

if __name__ == "__main__":
    target = input("Enter target IP: ")
    scanner = scan_target(target)
    generate_report(scanner, target)
    print("[+] Scan complete!")
